name: dart_bclibc
description: "Dart FFI bindings for the bclibc ballistics engine."
version: 0.2.0-beta.2
repository: https://github.com/ballistics-lab/dart-bclibc

environment:
  sdk: ^3.11.4

dependencies:
  ffi: ^2.2.0
  path: ^1.9.0

dev_dependencies:
  ffigen: ^20.1.1
  lints: ^6.0.0
  test: ^1.24.0
